;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-backward-conditional
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-fill-paragraph
        c-forward-conditional
        c-hungry-delete-backwards
        c-indent-line-or-region
        c-indent-new-comment-line
        clang-format-region-or-buffer
        dired-do-delete
        dired-flag-file-deletion
        electric-newline-and-maybe-indent
        helm-show-kill-ring
        indent-for-tab-command
        isearch-forward-regexp
        kill-region
        lux-fix-buffer
        lux-wrap-function
        markdown-exdent-or-delete
        orgtbl-self-insert-command
        smarter-move-beginning-of-line
        sp-backward-sexp
        sp-forward-sexp
        sp-remove-active-pair-overlay
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        c-toggle-auto-newline
        cleanup-region-or-buffer
        helm-M-x
        next-error
        recompile
        select-window-1
        select-window-2
        ))
