;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-backward-conditional
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-fill-paragraph
        c-forward-conditional
        c-indent-line-or-region
        clang-format-region-or-buffer
        dired-do-delete
        dired-flag-file-deletion
        electric-newline-and-maybe-indent
        indent-for-tab-command
        isearch-forward-regexp
        kill-region
        lux-fix-buffer
        lux-wrap-function
        markdown-exdent-or-delete
        orgtbl-self-insert-command
        smarter-move-beginning-of-line
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        ))
